[project]
name = "dbt-bixi-opendata"
version = "0.1.0"
description = "Rafinement de l'historique des locations de vélo en libre service de bixi Montréal"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.12",
    "dbt-duckdb>=1.11"
]


[dependency-groups]
dev = [
    "ruff>=0.16",
    "prek>=0.4.12", # pre-commit en rust
    # dbt stuff
    "shandy-sqlfmt[jinjafmt]>=0.28.2",
    "dbt-colibri>=0.2.7", # column lineage
]

[tool.sqlfmt]
exclude=["dbt/target/**/*", "dbt/dbt_packages/**/*"]
